version: '3.8'

services:
  app:
    build: .
    container_name: devtinder-app-container
    restart: always
    ports:
      - "27017:27017"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/dating-app
      - NODE_ENV=development
      - PORT=3000